/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author sanu
 */
public class AdmissionDetailForm extends javax.swing.JPanel {

    /**
     * Creates new form AdmissionDetailForm
     */
    public AdmissionDetailForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdmissionDetailFormPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        admissionIdLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateAdmittedLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateDischargedLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        patientIdLabel = new javax.swing.JLabel();
        wardIdLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nicLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bloodGroupLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        contactNoLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        sicknessHistoryLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Admission Detail Form");

        jLabel2.setText("Admission Id");

        admissionIdLabel.setText("-------------------------------------------------");

        jLabel4.setText("Date Admitted");

        dateAdmittedLabel.setText("--------------------------------------------");

        jLabel3.setText("Date Discharged");

        dateDischargedLabel.setText("--------------------------------------------");

        jLabel5.setText("Patient Id");

        jLabel6.setText("Ward Id");

        patientIdLabel.setText("-------------------------------------------------");

        wardIdLabel.setText("--------------------------------------------");

        jLabel7.setText("First Name");

        firstNameLabel.setText("------------------------------------------------");

        jLabel8.setText("Last Name");

        lastNameLabel.setText("------------------------------------------------");

        jLabel10.setText("NIC");

        nicLabel.setText("------------------------------------------------");

        jLabel12.setText("Gender");

        genderLabel.setText("------------------------------------------------");

        jLabel14.setText("Address");

        addressLabel.setText("-------------------------------------------------");

        jLabel16.setText("Age");

        ageLabel.setText("------------------------------------------------");

        jLabel9.setText("Incharge Doctor Id");

        jLabel11.setText("--------------------------------------------");

        jLabel13.setText("Blood Group");

        bloodGroupLabel.setText("------------------------------------------");

        jLabel15.setText("Contact Number");

        contactNoLabel.setText("--------------------------------------------");

        jLabel17.setText("Sickness history");

        sicknessHistoryLabel.setText("--------------------------------------------");

        javax.swing.GroupLayout AdmissionDetailFormPanelLayout = new javax.swing.GroupLayout(AdmissionDetailFormPanel);
        AdmissionDetailFormPanel.setLayout(AdmissionDetailFormPanelLayout);
        AdmissionDetailFormPanelLayout.setHorizontalGroup(
            AdmissionDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdmissionDetailFormPanelLayout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(457, 457, 457))
            .addGroup(AdmissionDetailFormPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(AdmissionDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addGap(75, 75, 75)
                .addGroup(AdmissionDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(admissionIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patientIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(198, 198, 198)
                .addGroup(AdmissionDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addGap(83, 83, 83)
                .addGroup(AdmissionDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wardIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateAdmittedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateDischargedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bloodGroupLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sicknessHistoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdmissionDetailFormPanelLayout.setVerticalGroup(
            AdmissionDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdmissionDetailFormPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(AdmissionDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(admissionIdLabel)
                    .addComponent(jLabel4)
                    .addComponent(dateAdmittedLabel))
                .addGap(32, 32, 32)
                .addGroup(AdmissionDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(patientIdLabel)
                    .addComponent(jLabel3)
                    .addComponent(dateDischargedLabel))
                .addGap(28, 28, 28)
                .addGroup(AdmissionDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(firstNameLabel)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addGap(30, 30, 30)
                .addGroup(AdmissionDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lastNameLabel)
                    .addComponent(jLabel6)
                    .addComponent(wardIdLabel))
                .addGap(28, 28, 28)
                .addGroup(AdmissionDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nicLabel)
                    .addComponent(jLabel13)
                    .addComponent(bloodGroupLabel))
                .addGap(35, 35, 35)
                .addGroup(AdmissionDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(genderLabel)
                    .addComponent(jLabel15)
                    .addComponent(contactNoLabel))
                .addGap(32, 32, 32)
                .addGroup(AdmissionDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(addressLabel)
                    .addComponent(jLabel17)
                    .addComponent(sicknessHistoryLabel))
                .addGap(32, 32, 32)
                .addGroup(AdmissionDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ageLabel))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdmissionDetailFormPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdmissionDetailFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdmissionDetailFormPanel;
    public static javax.swing.JLabel addressLabel;
    public static javax.swing.JLabel admissionIdLabel;
    public static javax.swing.JLabel ageLabel;
    public static javax.swing.JLabel bloodGroupLabel;
    public static javax.swing.JLabel contactNoLabel;
    public static javax.swing.JLabel dateAdmittedLabel;
    public static javax.swing.JLabel dateDischargedLabel;
    public static javax.swing.JLabel firstNameLabel;
    public static javax.swing.JLabel genderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel lastNameLabel;
    public static javax.swing.JLabel nicLabel;
    public static javax.swing.JLabel patientIdLabel;
    public static javax.swing.JLabel sicknessHistoryLabel;
    public static javax.swing.JLabel wardIdLabel;
    // End of variables declaration//GEN-END:variables
}
