/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClerkController;
import controller.EmployeeController;
import static controller.EmployeeController.getLastEmployeeId;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Clerk;
import model.Employee;
import javax.swing.JOptionPane;
import static view.Add.addPanel1;

/**
 *
 * @author sanu
 */
public class ClerkEntryForm extends javax.swing.JPanel {

    /**
     * Creates new form ClerkEntryForm
     */
    public ClerkEntryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        clerkEntryFormPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        clerkIdText = new javax.swing.JTextField();
        employeeIdText = new javax.swing.JTextField();
        nicText = new javax.swing.JTextField();
        firstNameText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        registrationDateText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        contactNumberText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressText = new javax.swing.JTextArea();
        submitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        genderCombo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();

        clerkEntryFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Clerk Entry Form");

        jLabel2.setText("Clerk ID");

        jLabel3.setText("Employee ID");

        jLabel4.setText("NIC");

        jLabel5.setText("First Name");

        jLabel6.setText("Last Name");

        jLabel7.setText("Gender");

        clerkIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clerkIdTextActionPerformed(evt);
            }
        });

        jLabel8.setText("Email");

        jLabel9.setText("Registration Date");

        jLabel10.setText("Address");

        jLabel11.setText("Contact Number");

        addressText.setColumns(20);
        addressText.setRows(5);
        jScrollPane1.setViewportView(addressText);

        submitButton.setBackground(new java.awt.Color(204, 204, 204));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clerk.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clerkEntryFormPanelLayout = new javax.swing.GroupLayout(clerkEntryFormPanel);
        clerkEntryFormPanel.setLayout(clerkEntryFormPanelLayout);
        clerkEntryFormPanelLayout.setHorizontalGroup(
            clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clerkEntryFormPanelLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(updateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(339, 339, 339)
                .addComponent(backButton)
                .addGap(50, 50, 50))
            .addGroup(clerkEntryFormPanelLayout.createSequentialGroup()
                .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clerkEntryFormPanelLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1))
                    .addGroup(clerkEntryFormPanelLayout.createSequentialGroup()
                        .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clerkEntryFormPanelLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(46, 46, 46))
                            .addGroup(clerkEntryFormPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(80, 80, 80)))
                        .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(clerkEntryFormPanelLayout.createSequentialGroup()
                                .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clerkEntryFormPanelLayout.createSequentialGroup()
                                        .addComponent(clerkIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(71, 71, 71))
                                    .addGroup(clerkEntryFormPanelLayout.createSequentialGroup()
                                        .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(193, 193, 193)))
                                .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(35, 35, 35)
                                .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(registrationDateText, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(contactNumberText)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(emailText, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                .addComponent(lastNameText, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(firstNameText)
                                .addComponent(nicText)
                                .addComponent(employeeIdText, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        clerkEntryFormPanelLayout.setVerticalGroup(
            clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clerkEntryFormPanelLayout.createSequentialGroup()
                .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clerkEntryFormPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clerkEntryFormPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28))
                            .addGroup(clerkEntryFormPanelLayout.createSequentialGroup()
                                .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clerkEntryFormPanelLayout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(employeeIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(38, 38, 38)
                                        .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(nicText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                        .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34)
                                        .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40))
                                    .addGroup(clerkEntryFormPanelLayout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel9)
                                            .addComponent(registrationDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(clerkIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40)
                                        .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(17, 17, 17)))
                                .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)))
                        .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clerkEntryFormPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)))
                .addGroup(clerkEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(backButton)
                    .addComponent(updateButton))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clerkEntryFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clerkEntryFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //String Employee_id_String = employeeIdText.getText();
        //int Employee_id = Integer.parseInt(Employee_id_String);
        //String Clerk_id_String = clerkIdText.getText();
        //int Clerk_id = Integer.parseInt(Clerk_id_String);
        String NIC = nicText.getText();
        String First_name = firstNameText.getText();
        String Last_name = lastNameText.getText();
        String Sex = (String)genderCombo.getSelectedItem();
        String Email = emailText.getText();
        String Registration_date = registrationDateText.getText();
        String Address = addressText.getText();
        String Contact_no = contactNumberText.getText();
        
        //Clerk clerk = new Clerk(Employee_id,Clerk_id);
        Clerk clerk = new Clerk(First_name,Last_name,NIC,Address,Sex,Contact_no,Registration_date,Email);
        try {
            clerk.setEmployee_id(getLastEmployeeId());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClerkEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ClerkEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        try {
            EmployeeController.addEmployee(clerk);
            boolean addClerk = ClerkController.addClerk(clerk);
            
            if(addClerk){
                JOptionPane.showMessageDialog(this, "Successful");
            }else{
                JOptionPane.showMessageDialog(this, "Failed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ClerkEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClerkEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Add add = new Add();
        add.addPanel1.setVisible(true);
        clerkEntryFormPanel.setLayout(new BorderLayout());
        clerkEntryFormPanel.removeAll();
        clerkEntryFormPanel.add(addPanel1);
        clerkEntryFormPanel.validate();
        clerkEntryFormPanel.repaint();
    }//GEN-LAST:event_backButtonActionPerformed

    private void clerkIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clerkIdTextActionPerformed
        //Auto fill Clerk entry form
        try {
            Clerk clerk = ClerkController.searchClerkDetail(clerkIdText.getText());
            if (clerk != null) {
                //ClerkDetailForm.clerkIdLabel.setText(getClerkIdText.getText());
                ClerkEntryForm.employeeIdText.setText(Integer.toString(clerk.getEmployee_Employee_id()));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DetailsGetClerkId.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DetailsGetClerkId.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        Employee employee = null;
        try {
            employee = EmployeeController.searchEmployeeDetail(employeeIdText.getText());
            if (employee != null) {
                //ClerkEntryForm.employeeIdLabel.setText(employeeIdLabel.getText());
                ClerkEntryForm.firstNameText.setText(employee.getFirst_name());
                ClerkEntryForm.lastNameText.setText(employee.getLast_name());
                ClerkEntryForm.nicText.setText(employee.getNIC());
                ClerkEntryForm.addressText.setText(employee.getAddress());
                ClerkEntryForm.genderCombo.setSelectedItem(employee.getSex());
                ClerkEntryForm.contactNumberText.setText(employee.getContact_no());
                ClerkEntryForm.registrationDateText.setText(employee.getRegistration_date());
                ClerkEntryForm.emailText.setText(employee.getEmail());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DetailsGetEmployeeId.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DetailsGetEmployeeId.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_clerkIdTextActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String Employee_id_String = employeeIdText.getText();
        int Employee_id = Integer.parseInt(Employee_id_String); 
        String Clerk_id_String = clerkIdText.getText();
        int Clerk_id = Integer.parseInt(Clerk_id_String); 
        String NIC = nicText.getText();
        String First_name = firstNameText.getText();
        String Last_name = lastNameText.getText();
        String Sex = (String)genderCombo.getSelectedItem();
        String Email = emailText.getText();
        String Registration_date = registrationDateText.getText();
        String Address = addressText.getText();
        String Contact_no = contactNumberText.getText();
        
        Clerk clerk = new Clerk(Clerk_id,Employee_id,First_name,Last_name,NIC,Address,Sex,Contact_no,Registration_date,Email);
        
        try {
            boolean updateEmployee=EmployeeController.updateEmployee(clerk);
            boolean updateClerk = ClerkController.UpdateClerk(clerk);
            if(updateClerk){
            JOptionPane.showMessageDialog(this, "Successful");
            }else{
            JOptionPane.showMessageDialog(this, "Failed");
            }
            if(updateEmployee){
            JOptionPane.showMessageDialog(this, "Su");
            }else{
            JOptionPane.showMessageDialog(this, "Fa");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ClerkEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClerkEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea addressText;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JPanel clerkEntryFormPanel;
    public static javax.swing.JTextField clerkIdText;
    public static javax.swing.JTextField contactNumberText;
    public static javax.swing.JTextField emailText;
    public static javax.swing.JTextField employeeIdText;
    public static javax.swing.JTextField firstNameText;
    public static javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField lastNameText;
    public static javax.swing.JTextField nicText;
    public static javax.swing.JTextField registrationDateText;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
