/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EmployeeController;
import controller.NurseController;
import controller.PatientController;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Employee;
import model.Nurse;
import model.Patient_record;
import static view.NurseDetailForm.employeeIdLabel;
import static view.NurseEntryForm.nurseIdText;

/**
 *
 * @author sanu
 */
public class DetailsGetNurseId extends javax.swing.JPanel {

    /**
     * Creates new form DetailsGetNurseId
     */
    public DetailsGetNurseId() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getNurseIdPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nurseIdText = new javax.swing.JTextField();
        nextButton = new javax.swing.JToggleButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Enter Nurse Id");

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout getNurseIdPanelLayout = new javax.swing.GroupLayout(getNurseIdPanel);
        getNurseIdPanel.setLayout(getNurseIdPanelLayout);
        getNurseIdPanelLayout.setHorizontalGroup(
            getNurseIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getNurseIdPanelLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(getNurseIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(getNurseIdPanelLayout.createSequentialGroup()
                        .addComponent(nurseIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(nextButton)))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        getNurseIdPanelLayout.setVerticalGroup(
            getNurseIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getNurseIdPanelLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(getNurseIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nurseIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextButton))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(getNurseIdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(getNurseIdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        NurseDetailForm adf = new NurseDetailForm();
        adf.setVisible(true);
        getNurseIdPanel.setLayout(new BorderLayout());
        getNurseIdPanel.removeAll();
        getNurseIdPanel.add(adf);
        getNurseIdPanel.validate();
        getNurseIdPanel.repaint();
        
        //Auto fill details to NurseDetailForm
        Nurse nurse;
        try {
            nurse = NurseController.searchNurseDetail(nurseIdText.getText());
            if (nurse != null) {
            NurseDetailForm.nurseIdLabel.setText(nurseIdText.getText());
            NurseDetailForm.wardIdLabel.setText(Integer.toString(nurse.getWard_Ward_id()));
            NurseDetailForm.employeeIdLabel.setText(Integer.toString(nurse.getEmployee_Employee_id()));
            NurseDetailForm.nurseTypeLabel.setText(nurse.getNurse_type());}
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DetailsGetNurseId.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DetailsGetNurseId.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Employee employee = null;
        try {
            employee = EmployeeController.searchEmployeeDetail(employeeIdLabel.getText());
            if (employee != null) {
                NurseDetailForm.employeeIdLabel.setText(employeeIdLabel.getText());
                NurseDetailForm.firstNameLabel.setText(employee.getFirst_name());
                NurseDetailForm.lastNameLabel.setText(employee.getLast_name());
                NurseDetailForm.nicLabel.setText(employee.getNIC());
                NurseDetailForm.addressLabel.setText(employee.getAddress());
                NurseDetailForm.genderLabel.setText(employee.getSex());
                NurseDetailForm.contactNumberLabel.setText(employee.getContact_no());
                NurseDetailForm.registrationDateLabel.setText(employee.getRegistration_date());
                NurseDetailForm.emailLabel.setText(employee.getEmail());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DetailsGetEmployeeId.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DetailsGetEmployeeId.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nextButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel getNurseIdPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton nextButton;
    private javax.swing.JTextField nurseIdText;
    // End of variables declaration//GEN-END:variables
}
