/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EmployeeController;
import controller.PatientController;
import controller.ReceptionistController;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Employee;
import model.Patient_record;
import model.Receptionist;
import static view.NurseDetailForm.employeeIdLabel;
import static view.ReceptionistDetailForm.getEmployeeIdLabel;
import static view.ReceptionistEntryForm.receptionistIdText;

/**
 *
 * @author sanu
 */
public class DetailsGetReceptionistId extends javax.swing.JPanel {

    /**
     * Creates new form DetailsGetReceptionistId
     */
    public DetailsGetReceptionistId() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getReceptionistIdPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        getReceptionistIdText = new javax.swing.JTextField();
        nextButton = new javax.swing.JToggleButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Enter Receptionist Id");

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout getReceptionistIdPanelLayout = new javax.swing.GroupLayout(getReceptionistIdPanel);
        getReceptionistIdPanel.setLayout(getReceptionistIdPanelLayout);
        getReceptionistIdPanelLayout.setHorizontalGroup(
            getReceptionistIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getReceptionistIdPanelLayout.createSequentialGroup()
                .addGroup(getReceptionistIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(getReceptionistIdPanelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(getReceptionistIdPanelLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(getReceptionistIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(nextButton)))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        getReceptionistIdPanelLayout.setVerticalGroup(
            getReceptionistIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getReceptionistIdPanelLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(getReceptionistIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getReceptionistIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextButton))
                .addContainerGap(280, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(getReceptionistIdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(getReceptionistIdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        ReceptionistDetailForm rdf = new ReceptionistDetailForm();
        rdf.setVisible(true);
        getReceptionistIdPanel.setLayout(new BorderLayout());
        getReceptionistIdPanel.removeAll();
        getReceptionistIdPanel.add(rdf);
        getReceptionistIdPanel.validate();
        getReceptionistIdPanel.repaint();
        
        Receptionist receptionist;
        try {
            receptionist = ReceptionistController.searchReceptionistDetail(getReceptionistIdText.getText());
            if (receptionist != null) {
            ReceptionistDetailForm.receptionistIdLabel.setText(getReceptionistIdText.getText());
            ReceptionistDetailForm.receptionistShiftLabel.setText(receptionist.getReceptionist_shift());
            ReceptionistDetailForm.getEmployeeIdLabel.setText(Integer.toString(receptionist.getEmployee_Employee_id()));}
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DetailsGetReceptionistId.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DetailsGetReceptionistId.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Employee employee = null;
        try {
            employee = EmployeeController.searchEmployeeDetail(getEmployeeIdLabel.getText());
            if (employee != null) {
                ReceptionistDetailForm.getEmployeeIdLabel.setText(getEmployeeIdLabel.getText());
                ReceptionistDetailForm.firstNameLabel.setText(employee.getFirst_name());
                ReceptionistDetailForm.lastNameLabel.setText(employee.getLast_name());
                ReceptionistDetailForm.nicLabel.setText(employee.getNIC());
                ReceptionistDetailForm.addressLabel.setText(employee.getAddress());
                ReceptionistDetailForm.genderLabel.setText(employee.getSex());
                ReceptionistDetailForm.contactNoLabel.setText(employee.getContact_no());
                ReceptionistDetailForm.registrationDateLabel.setText(employee.getRegistration_date());
                ReceptionistDetailForm.emailLabel.setText(employee.getEmail());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DetailsGetEmployeeId.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DetailsGetEmployeeId.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nextButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel getReceptionistIdPanel;
    public static javax.swing.JTextField getReceptionistIdText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton nextButton;
    // End of variables declaration//GEN-END:variables
}
