/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BillController;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Bill;

/**
 *
 * @author sanu
 */
public class DetailsGetBillId extends javax.swing.JPanel {

    /**
     * Creates new form DetailsGetBillId
     */
    public DetailsGetBillId() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getBillIdPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        getBillIdText = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Enter Bill Id");

        jToggleButton1.setText("Next");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout getBillIdPanelLayout = new javax.swing.GroupLayout(getBillIdPanel);
        getBillIdPanel.setLayout(getBillIdPanelLayout);
        getBillIdPanelLayout.setHorizontalGroup(
            getBillIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, getBillIdPanelLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(getBillIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(getBillIdPanelLayout.createSequentialGroup()
                        .addComponent(getBillIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jToggleButton1)))
                .addGap(271, 271, 271))
        );
        getBillIdPanelLayout.setVerticalGroup(
            getBillIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getBillIdPanelLayout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(getBillIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getBillIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1))
                .addGap(242, 242, 242))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(getBillIdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(getBillIdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        BillDetailForm adf = new BillDetailForm();
        adf.setVisible(true);
        getBillIdPanel.setLayout(new BorderLayout());
        getBillIdPanel.removeAll();
        getBillIdPanel.add(adf);
        getBillIdPanel.validate();
        getBillIdPanel.repaint();
        
        //Auto fill bill details when bill id given
        Bill bill;
        try {
            bill = BillController.searchBillDetail(getBillIdText.getText());
            if (bill != null) {
            BillDetailForm.billIdLabel.setText(getBillIdText.getText());
            BillDetailForm.medicineChargeLabel.setText(Double.toString(bill.getMedicine_charge()));
            BillDetailForm.roomChargeLabel.setText(Double.toString(bill.getRoom_charge()));
            BillDetailForm.operationChargeLabel.setText(Double.toString(bill.getOperation_charge()));
            BillDetailForm.doctorChargeLabel.setText(Double.toString(bill.getDoctor_charge()));
            BillDetailForm.labChargeLabel.setText(Double.toString(bill.getLab_charge()));
            BillDetailForm.nursingChargeLabel.setText(Double.toString(bill.getNursing_charge()));}
            //BillDetailForm.advanceLabel.setText(bill.getBlood_group());
            //BillDetailForm.dateLabel.setText(Integer.toString(bill.getContact_no()));
            //BillDetailForm.ChargeLabel.setText(bill.getSickness_history());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DetailsGetBillId.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DetailsGetBillId.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel getBillIdPanel;
    public static javax.swing.JTextField getBillIdText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
