/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AdmissionController;
import controller.EmployeeController;
import controller.PatientController;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Admission;
import model.Employee;
import model.Patient_record;
import static view.AdmissionDetailForm.patientIdLabel;
import static view.AdmissionEntryForm.admissionIdText;
import static view.NurseEntryForm.employeeIdText;

/**
 *
 * @author sanu
 */
public class DetailsGetAdmissionId extends javax.swing.JPanel {

    /**
     * Creates new form GetAdmissionId
     */
    public DetailsGetAdmissionId() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getAdmissionIdPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        admissionIdText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Enter Admission ID");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout getAdmissionIdPanelLayout = new javax.swing.GroupLayout(getAdmissionIdPanel);
        getAdmissionIdPanel.setLayout(getAdmissionIdPanelLayout);
        getAdmissionIdPanelLayout.setHorizontalGroup(
            getAdmissionIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getAdmissionIdPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(getAdmissionIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(getAdmissionIdPanelLayout.createSequentialGroup()
                        .addComponent(admissionIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        getAdmissionIdPanelLayout.setVerticalGroup(
            getAdmissionIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getAdmissionIdPanelLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(getAdmissionIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admissionIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(291, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(getAdmissionIdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(getAdmissionIdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AdmissionDetailForm adf = new AdmissionDetailForm();
        adf.setVisible(true);
        getAdmissionIdPanel.setLayout(new BorderLayout());
        getAdmissionIdPanel.removeAll();
        getAdmissionIdPanel.add(adf);
        getAdmissionIdPanel.validate();
        getAdmissionIdPanel.repaint();
        
        //Auto fill admission details when Admission_id is given to AdmissionDetailForm
       
            Admission admission;
        try {
            admission = AdmissionController.searchAdmissionDetail(admissionIdText.getText());
            if (admission != null) {
            AdmissionDetailForm.admissionIdLabel.setText(admissionIdText.getText());
            AdmissionDetailForm.patientIdLabel.setText(Integer.toString(admission.getPatient_record_Patient_id()));
            AdmissionDetailForm.wardIdLabel.setText(Integer.toString(admission.getWard_Ward_id()));
            AdmissionDetailForm.dateAdmittedLabel.setText(admission.getDate_admitted());
            AdmissionDetailForm.dateDischargedLabel.setText(admission.getDate_discharged());
            
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DetailsGetAdmissionId.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DetailsGetAdmissionId.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Auto fill details to Admission Detail Form
        Patient_record patientRecord;
        try {
            patientRecord = PatientController.searchPatientDetail(patientIdLabel.getText());
            if (patientRecord != null) {
            AdmissionDetailForm.patientIdLabel.setText(patientIdLabel.getText());
            AdmissionDetailForm.firstNameLabel.setText(patientRecord.getFirst_name());
            AdmissionDetailForm.lastNameLabel.setText(patientRecord.getLast_name());
            AdmissionDetailForm.nicLabel.setText(patientRecord.getNIC());
            AdmissionDetailForm.addressLabel.setText(patientRecord.getAddress());
            AdmissionDetailForm.genderLabel.setText(patientRecord.getSex());
            AdmissionDetailForm.ageLabel.setText(Integer.toString(patientRecord.getAge()));
            AdmissionDetailForm.bloodGroupLabel.setText(patientRecord.getBlood_group());
            AdmissionDetailForm.contactNoLabel.setText(Integer.toString(patientRecord.getContact_no()));
            AdmissionDetailForm.sicknessHistoryLabel.setText(patientRecord.getSickness_history());}
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DetailsGetAdmissionId.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DetailsGetAdmissionId.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField admissionIdText;
    private javax.swing.JPanel getAdmissionIdPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
