/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;

/**
 *
 * @author sanu
 */
public class Details extends javax.swing.JPanel {

    /**
     * Creates new form Details
     */
    public Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailsPanel1 = new javax.swing.JPanel();
        detailsPanel2 = new javax.swing.JPanel();
        patientButton = new javax.swing.JButton();
        admissionButton = new javax.swing.JButton();
        doctorbutton = new javax.swing.JButton();
        employeeButton = new javax.swing.JButton();
        nurseButton = new javax.swing.JButton();
        receptionistButton = new javax.swing.JButton();
        clerkButton = new javax.swing.JButton();
        billButton = new javax.swing.JButton();
        testButton = new javax.swing.JButton();
        detailsPanel3 = new javax.swing.JPanel();

        detailsPanel1.setBackground(new java.awt.Color(0, 204, 204));

        detailsPanel2.setBackground(new java.awt.Color(255, 102, 153));

        patientButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        patientButton.setText("Patient");
        patientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientButtonActionPerformed(evt);
            }
        });

        admissionButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        admissionButton.setText("Admission");
        admissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admissionButtonActionPerformed(evt);
            }
        });

        doctorbutton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        doctorbutton.setText("Doctor");
        doctorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorbuttonActionPerformed(evt);
            }
        });

        employeeButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        employeeButton.setText("Employee");
        employeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeButtonActionPerformed(evt);
            }
        });

        nurseButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nurseButton.setText("Nurse");
        nurseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurseButtonActionPerformed(evt);
            }
        });

        receptionistButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        receptionistButton.setText("Receptionist");
        receptionistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptionistButtonActionPerformed(evt);
            }
        });

        clerkButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        clerkButton.setText("Clerk");
        clerkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clerkButtonActionPerformed(evt);
            }
        });

        billButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        billButton.setText("Bill");
        billButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billButtonActionPerformed(evt);
            }
        });

        testButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        testButton.setText("Test");
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detailsPanel2Layout = new javax.swing.GroupLayout(detailsPanel2);
        detailsPanel2.setLayout(detailsPanel2Layout);
        detailsPanel2Layout.setHorizontalGroup(
            detailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admissionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(doctorbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(employeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nurseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(receptionistButton, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
            .addComponent(clerkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(billButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(testButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(patientButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        detailsPanel2Layout.setVerticalGroup(
            detailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(patientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(admissionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(doctorbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nurseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(receptionistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clerkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(billButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(testButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        detailsPanel3.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout detailsPanel3Layout = new javax.swing.GroupLayout(detailsPanel3);
        detailsPanel3.setLayout(detailsPanel3Layout);
        detailsPanel3Layout.setHorizontalGroup(
            detailsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        detailsPanel3Layout.setVerticalGroup(
            detailsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout detailsPanel1Layout = new javax.swing.GroupLayout(detailsPanel1);
        detailsPanel1.setLayout(detailsPanel1Layout);
        detailsPanel1Layout.setHorizontalGroup(
            detailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanel1Layout.createSequentialGroup()
                .addComponent(detailsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailsPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detailsPanel1Layout.setVerticalGroup(
            detailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailsPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(detailsPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void patientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientButtonActionPerformed
        DetailsGetPatientId pdfpi = new DetailsGetPatientId();
        pdfpi.setVisible(true);
        detailsPanel3.setLayout(new BorderLayout());
        detailsPanel3.removeAll();
        detailsPanel3.add(pdfpi);
        detailsPanel3.validate();
        detailsPanel3.repaint();
    }//GEN-LAST:event_patientButtonActionPerformed

    private void admissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admissionButtonActionPerformed
        DetailsGetAdmissionId gai = new DetailsGetAdmissionId();
        gai.setVisible(true);
        detailsPanel3.setLayout(new BorderLayout());
        detailsPanel3.removeAll();
        detailsPanel3.add(gai);
        detailsPanel3.validate();
        detailsPanel3.repaint();
    }//GEN-LAST:event_admissionButtonActionPerformed

    private void employeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeButtonActionPerformed
        DetailsGetEmployeeId gei = new DetailsGetEmployeeId();
        gei.setVisible(true);
        detailsPanel3.setLayout(new BorderLayout());
        detailsPanel3.removeAll();
        detailsPanel3.add(gei);
        detailsPanel3.validate();
        detailsPanel3.repaint();
    }//GEN-LAST:event_employeeButtonActionPerformed

    private void doctorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorbuttonActionPerformed
        DetailsGetDoctorId gdi = new DetailsGetDoctorId();
        gdi.setVisible(true);
        detailsPanel3.setLayout(new BorderLayout());
        detailsPanel3.removeAll();
        detailsPanel3.add(gdi);
        detailsPanel3.validate();
        detailsPanel3.repaint();
    }//GEN-LAST:event_doctorbuttonActionPerformed

    private void nurseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurseButtonActionPerformed
        DetailsGetNurseId gni = new DetailsGetNurseId();
        gni.setVisible(true);
        detailsPanel3.setLayout(new BorderLayout());
        detailsPanel3.removeAll();
        detailsPanel3.add(gni);
        detailsPanel3.validate();
        detailsPanel3.repaint();
    }//GEN-LAST:event_nurseButtonActionPerformed

    private void clerkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clerkButtonActionPerformed
        DetailsGetClerkId gci = new DetailsGetClerkId();
        gci.setVisible(true);
        detailsPanel3.setLayout(new BorderLayout());
        detailsPanel3.removeAll();
        detailsPanel3.add(gci);
        detailsPanel3.validate();
        detailsPanel3.repaint();
    }//GEN-LAST:event_clerkButtonActionPerformed

    private void receptionistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptionistButtonActionPerformed
        DetailsGetReceptionistId gri = new DetailsGetReceptionistId();
        gri.setVisible(true);
        detailsPanel3.setLayout(new BorderLayout());
        detailsPanel3.removeAll();
        detailsPanel3.add(gri);
        detailsPanel3.validate();
        detailsPanel3.repaint();
    }//GEN-LAST:event_receptionistButtonActionPerformed

    private void billButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billButtonActionPerformed
        DetailsGetBillId gbi = new DetailsGetBillId();
        gbi.setVisible(true);
        detailsPanel3.setLayout(new BorderLayout());
        detailsPanel3.removeAll();
        detailsPanel3.add(gbi);
        detailsPanel3.validate();
        detailsPanel3.repaint();
    }//GEN-LAST:event_billButtonActionPerformed

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
        DetailsGetTestId gti = new DetailsGetTestId();
        gti.setVisible(true);
        detailsPanel3.setLayout(new BorderLayout());
        detailsPanel3.removeAll();
        detailsPanel3.add(gti);
        detailsPanel3.validate();
        detailsPanel3.repaint();
    }//GEN-LAST:event_testButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admissionButton;
    private javax.swing.JButton billButton;
    private javax.swing.JButton clerkButton;
    private javax.swing.JPanel detailsPanel1;
    private javax.swing.JPanel detailsPanel2;
    public static javax.swing.JPanel detailsPanel3;
    private javax.swing.JButton doctorbutton;
    private javax.swing.JButton employeeButton;
    private javax.swing.JButton nurseButton;
    private javax.swing.JButton patientButton;
    private javax.swing.JButton receptionistButton;
    private javax.swing.JButton testButton;
    // End of variables declaration//GEN-END:variables
}
