/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PatientController;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Patient_record;

/**
 *
 * @author sanu
 */
public class DetailsGetPatientId extends javax.swing.JPanel {

    /**
     * Creates new form PatientDetailFormPatientId
     */
    public DetailsGetPatientId() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientDetailFormPatientIdPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        patientIdText = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();

        jLabel1.setText("Patient Id ");

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patientDetailFormPatientIdPanelLayout = new javax.swing.GroupLayout(patientDetailFormPatientIdPanel);
        patientDetailFormPatientIdPanel.setLayout(patientDetailFormPatientIdPanelLayout);
        patientDetailFormPatientIdPanelLayout.setHorizontalGroup(
            patientDetailFormPatientIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientDetailFormPatientIdPanelLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(patientIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(nextButton)
                .addContainerGap(450, Short.MAX_VALUE))
        );
        patientDetailFormPatientIdPanelLayout.setVerticalGroup(
            patientDetailFormPatientIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientDetailFormPatientIdPanelLayout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addGroup(patientDetailFormPatientIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(patientIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextButton))
                .addContainerGap(294, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientDetailFormPatientIdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientDetailFormPatientIdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        PatientDetailForm pdf = new PatientDetailForm();
        pdf.setVisible(true);
        patientDetailFormPatientIdPanel.setLayout(new BorderLayout());
        patientDetailFormPatientIdPanel.removeAll();
        patientDetailFormPatientIdPanel.add(pdf);
        patientDetailFormPatientIdPanel.validate();
        patientDetailFormPatientIdPanel.repaint();
        
        //Auto fill patient details when patient id is given to PatientDetailForm
        try {
            Patient_record patientRecord = PatientController.searchPatientDetail(patientIdText.getText());
            if (patientRecord != null) {
            PatientDetailForm.patientIdLabel.setText(patientIdText.getText());
            PatientDetailForm.firstNameLabel.setText(patientRecord.getFirst_name());
            PatientDetailForm.lastNameLabel.setText(patientRecord.getLast_name());
            PatientDetailForm.nicLabel.setText(patientRecord.getNIC());
            PatientDetailForm.addressLabel.setText(patientRecord.getAddress());
            PatientDetailForm.genderLabel.setText(patientRecord.getSex());
            PatientDetailForm.ageLabel.setText(Integer.toString(patientRecord.getAge()));
            PatientDetailForm.bloodGroupLabel.setText(patientRecord.getBlood_group());
            PatientDetailForm.contactNoLabel.setText(Integer.toString(patientRecord.getContact_no()));
            PatientDetailForm.sicknessHistoryLabel.setText(patientRecord.getSickness_history());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewAdmissionGetPatientId.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewAdmissionGetPatientId.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nextButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nextButton;
    private javax.swing.JPanel patientDetailFormPatientIdPanel;
    public static javax.swing.JTextField patientIdText;
    // End of variables declaration//GEN-END:variables
}
