/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author sanu
 */
public class DoctorDetailForm extends javax.swing.JPanel {

    /**
     * Creates new form DoctorDetailForm
     */
    public DoctorDetailForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorDetailFormPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        doctorIdLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        employeeIdLabel = new javax.swing.JLabel();
        qualificationsLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nicLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        registrationDateLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        contactNumberLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Doctor Detail Form");

        jLabel2.setText("Doctor Id");

        doctorIdLabel.setText("---------------------------------------------------");

        jLabel4.setText("Qualifications");

        jLabel5.setText("Employee Id");

        employeeIdLabel.setText("---------------------------------------------------");

        qualificationsLabel.setText("---------------------------------------------------");

        jLabel3.setText("NIC");

        jLabel6.setText("First Name");

        jLabel7.setText("Last Name");

        jLabel8.setText("Gender");

        jLabel9.setText("Address");

        nicLabel.setText("---------------------------------------------------");

        firstNameLabel.setText("---------------------------------------------------");

        lastNameLabel.setText("---------------------------------------------------");

        sexLabel.setText("---------------------------------------------------");

        addressLabel.setText("---------------------------------------------------");

        jLabel10.setText("Registration Date");

        registrationDateLabel.setText("--------------------------------------------------");

        jLabel12.setText("Contact Number");

        contactNumberLabel.setText("---------------------------------------------------");

        jLabel14.setText("Email");

        emailLabel.setText("---------------------------------------------------");

        javax.swing.GroupLayout doctorDetailFormPanelLayout = new javax.swing.GroupLayout(doctorDetailFormPanel);
        doctorDetailFormPanel.setLayout(doctorDetailFormPanelLayout);
        doctorDetailFormPanelLayout.setHorizontalGroup(
            doctorDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doctorDetailFormPanelLayout.createSequentialGroup()
                .addContainerGap(372, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(302, 302, 302))
            .addGroup(doctorDetailFormPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(doctorDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(54, 54, 54)
                .addGroup(doctorDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(doctorIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(employeeIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sexLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(93, 93, 93)
                .addGroup(doctorDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addGap(32, 32, 32)
                .addGroup(doctorDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registrationDateLabel)
                    .addComponent(qualificationsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(contactNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        doctorDetailFormPanelLayout.setVerticalGroup(
            doctorDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorDetailFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(doctorDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(employeeIdLabel)
                    .addComponent(jLabel10)
                    .addComponent(registrationDateLabel))
                .addGap(38, 38, 38)
                .addGroup(doctorDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorIdLabel)
                    .addComponent(jLabel4)
                    .addComponent(qualificationsLabel)
                    .addComponent(jLabel2))
                .addGap(43, 43, 43)
                .addGroup(doctorDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nicLabel)
                    .addComponent(jLabel12)
                    .addComponent(contactNumberLabel))
                .addGap(38, 38, 38)
                .addGroup(doctorDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(firstNameLabel)
                    .addComponent(jLabel14)
                    .addComponent(emailLabel))
                .addGap(37, 37, 37)
                .addGroup(doctorDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lastNameLabel))
                .addGap(40, 40, 40)
                .addGroup(doctorDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sexLabel))
                .addGap(44, 44, 44)
                .addGroup(doctorDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(addressLabel))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doctorDetailFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doctorDetailFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel addressLabel;
    public static javax.swing.JLabel contactNumberLabel;
    private javax.swing.JPanel doctorDetailFormPanel;
    public static javax.swing.JLabel doctorIdLabel;
    public static javax.swing.JLabel emailLabel;
    public static javax.swing.JLabel employeeIdLabel;
    public static javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel lastNameLabel;
    public static javax.swing.JLabel nicLabel;
    public static javax.swing.JLabel qualificationsLabel;
    public static javax.swing.JLabel registrationDateLabel;
    public static javax.swing.JLabel sexLabel;
    // End of variables declaration//GEN-END:variables
}
