/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DoctorController;
import controller.EmployeeController;
import static controller.EmployeeController.getLastEmployeeId;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Doctor;
import model.Employee;
import javax.swing.JOptionPane;
import static view.Add.addPanel1;
import static view.DetailsGetDoctorId.getDoctorIdText;
import static view.DoctorDetailForm.employeeIdLabel;

/**
 *
 * @author sanu
 */
public class DoctorEntryForm extends javax.swing.JPanel {

    /**
     * Creates new form DoctorEntryForm
     */
    public DoctorEntryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        doctorEntryFormPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        employeeIdText = new javax.swing.JTextField();
        doctorIdText = new javax.swing.JTextField();
        nicText = new javax.swing.JTextField();
        firstNameText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        registrationDateText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        qualificationsText = new javax.swing.JTextArea();
        submitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        contactNumberText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressText = new javax.swing.JTextArea();
        sexCombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        doctorEntryFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Doctor Entry Form");

        jLabel2.setText("Employee ID");

        jLabel3.setText("Doctor ID");

        jLabel4.setText("NIC");

        jLabel5.setText("First Name");

        jLabel6.setText("Last Name");

        jLabel7.setText("Sex");

        jLabel8.setText("Email");

        employeeIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeIdTextActionPerformed(evt);
            }
        });

        doctorIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorIdTextActionPerformed(evt);
            }
        });

        jLabel9.setText("Registration Date");

        jLabel10.setText("Address");

        qualificationsText.setColumns(20);
        qualificationsText.setRows(5);
        jScrollPane1.setViewportView(qualificationsText);

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("Contact Number");

        jLabel13.setText("Qualifications");

        addressText.setColumns(20);
        addressText.setRows(5);
        jScrollPane2.setViewportView(addressText);

        sexCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doctor.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout doctorEntryFormPanelLayout = new javax.swing.GroupLayout(doctorEntryFormPanel);
        doctorEntryFormPanel.setLayout(doctorEntryFormPanelLayout);
        doctorEntryFormPanelLayout.setHorizontalGroup(
            doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorEntryFormPanelLayout.createSequentialGroup()
                .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(doctorEntryFormPanelLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(doctorEntryFormPanelLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jButton1)
                        .addGap(169, 169, 169)
                        .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(doctorEntryFormPanelLayout.createSequentialGroup()
                                .addComponent(submitButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backButton))
                            .addGroup(doctorEntryFormPanelLayout.createSequentialGroup()
                                .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(doctorEntryFormPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(doctorEntryFormPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeeIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(doctorEntryFormPanelLayout.createSequentialGroup()
                                .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10))
                                .addGap(40, 40, 40)
                                .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nicText)
                                    .addComponent(firstNameText)
                                    .addComponent(lastNameText)
                                    .addGroup(doctorEntryFormPanelLayout.createSequentialGroup()
                                        .addComponent(sexCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(doctorIdText))))
                        .addGap(111, 111, 111)
                        .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(doctorEntryFormPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(37, 37, 37)
                                .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emailText)
                                    .addComponent(contactNumberText)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(registrationDateText))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        doctorEntryFormPanelLayout.setVerticalGroup(
            doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorEntryFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(employeeIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(registrationDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(doctorEntryFormPanelLayout.createSequentialGroup()
                        .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(doctorEntryFormPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(doctorIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(doctorEntryFormPanelLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(nicText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)))
                                    .addGroup(doctorEntryFormPanelLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel13)))
                                .addGap(28, 28, 28)
                                .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(36, 36, 36)
                                .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(sexCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doctorEntryFormPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(doctorEntryFormPanelLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doctorEntryFormPanelLayout.createSequentialGroup()
                                .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(doctorEntryFormPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(56, 56, 56))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doctorEntryFormPanelLayout.createSequentialGroup()
                                        .addComponent(contactNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)))
                                .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70))))
                    .addGroup(doctorEntryFormPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(doctorEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(backButton)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doctorEntryFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(doctorEntryFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //String Employee_id_String = employeeIdText.getText();
        //int Employee_id = Integer.parseInt(Employee_id_String);
        //String Doctor_id_String = doctorIdText.getText();
        //int Doctor_id = Integer.parseInt(Doctor_id_String);
        String First_name = firstNameText.getText();  
        String Last_name = lastNameText.getText();
        String NIC = nicText.getText();
        String Address = addressText.getText();
        String Sex = (String)sexCombo.getSelectedItem();
        String Contact_no = contactNumberText.getText();  
        String Registration_date = registrationDateText.getText();
        String Email = emailText.getText();  
        String Qualifications = qualificationsText.getText();  
        
        
       
        Doctor doctor = new Doctor(First_name,Last_name,NIC,Address,Sex,Contact_no,Registration_date,Email,Qualifications);
        try {
            doctor.setEmployee_id(getLastEmployeeId());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DoctorEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DoctorEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            EmployeeController.addEmployee(doctor);
            boolean addDoctor = DoctorController.addDoctor(doctor);
            if(addDoctor){
                JOptionPane.showMessageDialog(this, "Successful");
            }else{
                JOptionPane.showMessageDialog(this, "Failed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(DoctorEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DoctorEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void doctorIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorIdTextActionPerformed
        //Auto fill doctor details to DoctorEntryForm
        Doctor doctor;
        try {
            doctor = DoctorController.searchDoctorDetail(doctorIdText.getText());
            if (doctor != null) {
                //DoctorEntryForm.doctorIdText.setText(doctorIdText.getText());
                DoctorEntryForm.employeeIdText.setText(Integer.toString(doctor.getEmployee_Employee_id()));
                DoctorEntryForm.qualificationsText.setText(doctor.getQualifications());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DetailsGetDoctorId.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DetailsGetDoctorId.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        Employee employee = null;
        try {
            employee = EmployeeController.searchEmployeeDetail(employeeIdText.getText());
            if (employee != null) {
                DoctorEntryForm.employeeIdText.setText(employeeIdText.getText());
                DoctorEntryForm.firstNameText.setText(employee.getFirst_name());
                DoctorEntryForm.lastNameText.setText(employee.getLast_name());
                DoctorEntryForm.nicText.setText(employee.getNIC());
                DoctorEntryForm.addressText.setText(employee.getAddress());
                DoctorEntryForm.sexCombo.setSelectedItem(employee.getSex());
                DoctorEntryForm.contactNumberText.setText(employee.getContact_no());
                DoctorEntryForm.registrationDateText.setText(employee.getRegistration_date());
                DoctorEntryForm.emailText.setText(employee.getEmail());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DetailsGetEmployeeId.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DetailsGetEmployeeId.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_doctorIdTextActionPerformed

    private void employeeIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeIdTextActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Add add = new Add();
        add.addPanel1.setVisible(true);
        doctorEntryFormPanel.setLayout(new BorderLayout());
        doctorEntryFormPanel.removeAll();
        doctorEntryFormPanel.add(addPanel1);
        doctorEntryFormPanel.validate();
        doctorEntryFormPanel.repaint();
    }//GEN-LAST:event_backButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Employee_id_String = employeeIdText.getText();
        int Employee_id = Integer.parseInt(Employee_id_String); 
        String Doctor_id_String = doctorIdText.getText();
        int Doctor_id = Integer.parseInt(Doctor_id_String); 
        String NIC = nicText.getText();
        String First_name = firstNameText.getText();
        String Last_name = lastNameText.getText();
        String Sex = (String)sexCombo.getSelectedItem();
        String Email = emailText.getText();
        String Registration_date = registrationDateText.getText();
        String Address = addressText.getText();
        String Qualifications = qualificationsText.getText();
        String Contact_no = contactNumberText.getText();
        
        Doctor doctor = new Doctor(Doctor_id,Qualifications,Employee_id, First_name, Last_name, NIC, Address, Sex, Contact_no, Registration_date, Email);
        
        try {
            boolean updateEmployee=EmployeeController.updateEmployee(doctor);
            boolean updateDoctor = DoctorController.UpdateDoctor(doctor);
            if(updateDoctor){
            JOptionPane.showMessageDialog(this, "Successful");
            }else{
            JOptionPane.showMessageDialog(this, "Failed");
            }
            if(updateEmployee){
            JOptionPane.showMessageDialog(this, "Su");
            }else{
            JOptionPane.showMessageDialog(this, "Fa");
            }
        } catch (SQLException ex) {
            Logger.getLogger(DoctorEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DoctorEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea addressText;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JTextField contactNumberText;
    private javax.swing.JPanel doctorEntryFormPanel;
    public static javax.swing.JTextField doctorIdText;
    public static javax.swing.JTextField emailText;
    public static javax.swing.JTextField employeeIdText;
    public static javax.swing.JTextField firstNameText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextField lastNameText;
    public static javax.swing.JTextField nicText;
    public static javax.swing.JTextArea qualificationsText;
    public static javax.swing.JTextField registrationDateText;
    public static javax.swing.JComboBox<String> sexCombo;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
