/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author sanu
 */
public class NurseDetailForm extends javax.swing.JPanel {

    /**
     * Creates new form NurseDetailForm
     */
    public NurseDetailForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nurseDetailFormPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nurseIdLabel = new javax.swing.JLabel();
        wardIdLabel = new javax.swing.JLabel();
        nurseTypeLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        employeeIdLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nicLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        registrationDateLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        contactNumberLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Nurse Detail Form");

        jLabel2.setText("Nurse ID");

        jLabel3.setText("Ward Id");

        jLabel4.setText("Nurse Type");

        nurseIdLabel.setText("---------------------------------------------------");

        wardIdLabel.setText("--------------------------------------------------");

        nurseTypeLabel.setText("----------------------------------------------------------");

        jLabel5.setText("Employee ID");

        employeeIdLabel.setText("---------------------------------------------------");

        jLabel6.setText("NIC");

        nicLabel.setText("---------------------------------------------------");

        jLabel7.setText("First Name");

        firstNameLabel.setText("--------------------------------------------------");

        jLabel9.setText("Last Name");

        jLabel10.setText("Gender");

        lastNameLabel.setText("-------------------------------------------------");

        genderLabel.setText("-------------------------------------------------");

        jLabel8.setText("Registration Date");

        registrationDateLabel.setText("----------------------------------------------------------");

        jLabel12.setText("Address");

        addressLabel.setText("----------------------------------------------------------");

        jLabel11.setText("Contact Number");

        contactNumberLabel.setText("----------------------------------------------------------");

        jLabel13.setText("Email");

        emailLabel.setText("----------------------------------------------------------");

        javax.swing.GroupLayout nurseDetailFormPanelLayout = new javax.swing.GroupLayout(nurseDetailFormPanel);
        nurseDetailFormPanel.setLayout(nurseDetailFormPanelLayout);
        nurseDetailFormPanelLayout.setHorizontalGroup(
            nurseDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nurseDetailFormPanelLayout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(311, 311, 311))
            .addGroup(nurseDetailFormPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(nurseDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(nurseDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nurseDetailFormPanelLayout.createSequentialGroup()
                        .addGroup(nurseDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nurseIdLabel)
                            .addComponent(employeeIdLabel)
                            .addComponent(wardIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nicLabel)
                            .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameLabel))
                        .addGap(137, 137, 137)
                        .addGroup(nurseDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addGap(42, 42, 42)
                        .addGroup(nurseDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registrationDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(nurseDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addressLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(nurseTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(contactNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(genderLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nurseDetailFormPanelLayout.setVerticalGroup(
            nurseDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nurseDetailFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(nurseDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(employeeIdLabel)
                    .addComponent(jLabel8)
                    .addComponent(registrationDateLabel))
                .addGap(38, 38, 38)
                .addGroup(nurseDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nurseIdLabel)
                    .addComponent(jLabel12)
                    .addComponent(addressLabel))
                .addGap(37, 37, 37)
                .addGroup(nurseDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(wardIdLabel)
                    .addComponent(jLabel4)
                    .addComponent(nurseTypeLabel))
                .addGap(40, 40, 40)
                .addGroup(nurseDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nicLabel)
                    .addComponent(contactNumberLabel)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(nurseDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(firstNameLabel)
                    .addComponent(jLabel13)
                    .addComponent(emailLabel))
                .addGap(33, 33, 33)
                .addGroup(nurseDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lastNameLabel))
                .addGap(35, 35, 35)
                .addGroup(nurseDetailFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(genderLabel))
                .addGap(171, 171, 171))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nurseDetailFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nurseDetailFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel addressLabel;
    public static javax.swing.JLabel contactNumberLabel;
    public static javax.swing.JLabel emailLabel;
    public static javax.swing.JLabel employeeIdLabel;
    public static javax.swing.JLabel firstNameLabel;
    public static javax.swing.JLabel genderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel lastNameLabel;
    public static javax.swing.JLabel nicLabel;
    private javax.swing.JPanel nurseDetailFormPanel;
    public static javax.swing.JLabel nurseIdLabel;
    public static javax.swing.JLabel nurseTypeLabel;
    public static javax.swing.JLabel registrationDateLabel;
    public static javax.swing.JLabel wardIdLabel;
    // End of variables declaration//GEN-END:variables
}
