/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.EmployeeController;
import static controller.EmployeeController.getLastEmployeeId;
import controller.NurseController;
import java.awt.BorderLayout;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import database.DBConnection;
import model.Employee;
import model.Nurse;
import javax.swing.JOptionPane;
import static view.Add.addPanel1;
/**
 *
 * @author sanu
 */
public class NurseEntryForm extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NurseEntryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nurseEntryFormPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        employeeIdText = new javax.swing.JTextField();
        nurseIdText = new javax.swing.JTextField();
        nicText = new javax.swing.JTextField();
        firstNameText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        registrationDateText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressText = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        nurseTypeText = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        backButton = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        contactNumberText = new javax.swing.JTextField();
        genderCombo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        wardIdCombo = new javax.swing.JComboBox<>();

        nurseEntryFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nurse Entry Form");

        jLabel2.setText("Employee_id");

        jLabel3.setText("Nurse_id");

        jLabel4.setText("NIC");

        jLabel5.setText("First Name");

        jLabel6.setText("Last Name");

        jLabel7.setText("Gender");

        jLabel8.setText("Email");

        nurseIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurseIdTextActionPerformed(evt);
            }
        });

        firstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextActionPerformed(evt);
            }
        });

        jLabel9.setText("Registration Date");

        registrationDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationDateTextActionPerformed(evt);
            }
        });

        jLabel10.setText("Address");

        addressText.setColumns(20);
        addressText.setRows(5);
        jScrollPane1.setViewportView(addressText);

        jLabel11.setText("Nurse Type");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("Contact Number");

        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel13.setText("Ward_id");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Nurse (2).jpg"))); // NOI18N

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        wardIdCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        javax.swing.GroupLayout nurseEntryFormPanelLayout = new javax.swing.GroupLayout(nurseEntryFormPanel);
        nurseEntryFormPanel.setLayout(nurseEntryFormPanelLayout);
        nurseEntryFormPanelLayout.setHorizontalGroup(
            nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nurseEntryFormPanelLayout.createSequentialGroup()
                .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nurseEntryFormPanelLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1))
                    .addGroup(nurseEntryFormPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))
                        .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nurseEntryFormPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(nurseEntryFormPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wardIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nicText, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                        .addComponent(nurseIdText)
                                        .addComponent(employeeIdText)
                                        .addComponent(firstNameText)
                                        .addComponent(lastNameText)
                                        .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(88, 88, 88)
                        .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nurseEntryFormPanelLayout.createSequentialGroup()
                                .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9))
                                .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(nurseEntryFormPanelLayout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                            .addComponent(registrationDateText)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nurseEntryFormPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nurseTypeText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(contactNumberText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel10)))
                    .addGroup(nurseEntryFormPanelLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(submitButton)
                        .addGap(168, 168, 168)
                        .addComponent(updateButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nurseEntryFormPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(57, 57, 57))
        );
        nurseEntryFormPanelLayout.setVerticalGroup(
            nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nurseEntryFormPanelLayout.createSequentialGroup()
                .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nurseEntryFormPanelLayout.createSequentialGroup()
                        .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nurseEntryFormPanelLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(nurseIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(nurseEntryFormPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(wardIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(nicText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(nurseTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(contactNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(nurseEntryFormPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(employeeIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(registrationDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(nurseEntryFormPanelLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(nurseEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submitButton)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nurseEntryFormPanelLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(updateButton))))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nurseEntryFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nurseEntryFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //String Employee_id_String = employeeIdText.getText();
        //int Employee_id = Integer.parseInt(Employee_id_String);
        //String Nurse_id_String = nurseIdText.getText();
        //int Nurse_id = Integer.parseInt(Nurse_id_String);
        //String Ward_id_String = wardIdText.getText();
        //int Ward_id = Integer.parseInt(Ward_id_String);
        String NIC = nicText.getText();
        String First_name = firstNameText.getText();
        String Last_name = lastNameText.getText();
        String Sex = (String)genderCombo.getSelectedItem();
        String Email = emailText.getText();
        String Registration_date = registrationDateText.getText();
        String Address = addressText.getText();
        String Nurse_type = nurseTypeText.getText();
        String Contact_no = contactNumberText.getText();
        String Ward_id_String = (String)wardIdCombo.getSelectedItem();
        int Ward_id = Integer.parseInt(Ward_id_String);
                
        //Employee employee = new Employee(Employee_id,First_name,Last_name,NIC,Address,Sex,Contact_no,Registration_date,Email);
        //Nurse nurse = new Nurse(Nurse_id,Nurse_type,Employee_id,Ward_id);
        Nurse nurse = null;
        try {
            nurse = new Nurse(Ward_id, First_name, Last_name, NIC, Address, Sex, Contact_no, Registration_date, Email,Nurse_type);
            nurse.setEmployee_id(getLastEmployeeId());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NurseEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NurseEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
               
      
        boolean addNurse;
        try {
            EmployeeController.addEmployee(nurse);
            addNurse = NurseController.addNurse(nurse);
            if(addNurse){
            JOptionPane.showMessageDialog(this, "Successful");
            }else{
            JOptionPane.showMessageDialog(this, "Failed");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            Logger.getLogger(NurseEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NurseEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
    }//GEN-LAST:event_submitButtonActionPerformed

    private void firstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextActionPerformed

    private void registrationDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationDateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrationDateTextActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Add add = new Add();
        
        add.addPanel1.setVisible(true);
        nurseEntryFormPanel.setLayout(new BorderLayout());
        nurseEntryFormPanel.removeAll();
        nurseEntryFormPanel.add(addPanel1);
        nurseEntryFormPanel.validate();
        nurseEntryFormPanel.repaint();
    }//GEN-LAST:event_backButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String Employee_id_String = employeeIdText.getText();
        int Employee_id = Integer.parseInt(Employee_id_String); 
        String Nurse_id_String = nurseIdText.getText();
        int Nurse_id = Integer.parseInt(Nurse_id_String); 
        String NIC = nicText.getText();
        String First_name = firstNameText.getText();
        String Last_name = lastNameText.getText();
        String Sex = (String)genderCombo.getSelectedItem();
        String Email = emailText.getText();
        String Registration_date = registrationDateText.getText();
        String Address = addressText.getText();
        String Nurse_type = nurseTypeText.getText();
        String Contact_no = contactNumberText.getText();
        String Ward_id_String = (String)wardIdCombo.getSelectedItem();
        int Ward_id = Integer.parseInt(Ward_id_String);
        
        Nurse nurse = new Nurse(Nurse_id,Nurse_type,Ward_id,Employee_id, First_name, Last_name, NIC, Address, Sex, Contact_no, Registration_date, Email);
        
        //Update Nurse
        try {
            boolean updateEmployee=EmployeeController.updateEmployee(nurse);
            boolean updateNurse = NurseController.UpdateNurse(nurse);
            if(updateNurse){
            JOptionPane.showMessageDialog(this, "Successful");
            }else{
            JOptionPane.showMessageDialog(this, "Failed");
            }
            if(updateEmployee){
            JOptionPane.showMessageDialog(this, "Su");
            }else{
            JOptionPane.showMessageDialog(this, "Fa");
            }
        } catch (SQLException ex) {
            Logger.getLogger(NurseEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NurseEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*UpdateGetNurseId ugni = new UpdateGetNurseId();
        ugni.setVisible(true);
        nurseEntryFormPanel.setLayout(new BorderLayout());
        nurseEntryFormPanel.removeAll();
        nurseEntryFormPanel.add(ugni);
        nurseEntryFormPanel.validate();
        nurseEntryFormPanel.repaint();*/
        
    }//GEN-LAST:event_updateButtonActionPerformed
    //Auto fill details When nurse id given
    private void nurseIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurseIdTextActionPerformed
        
        Nurse nurse;
        try {
            nurse = NurseController.searchNurseDetail(nurseIdText.getText());
            if (nurse != null) {
            //NurseEntryForm.nurseIdText.setText(nurseIdText.getText());
            NurseEntryForm.wardIdCombo.setSelectedItem(nurse.getWard_Ward_id());
            NurseEntryForm.employeeIdText.setText(Integer.toString(nurse.getEmployee_Employee_id()));
            NurseEntryForm.nurseTypeText.setText(nurse.getNurse_type());}
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DetailsGetNurseId.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DetailsGetNurseId.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Employee employee = null;
        try {
            employee = EmployeeController.searchEmployeeDetail(employeeIdText.getText());
            if (employee != null) {
                //NurseEntryForm.employeeIdLabel.setText(employeeIdLabel.getText());
                NurseEntryForm.firstNameText.setText(employee.getFirst_name());
                NurseEntryForm.lastNameText.setText(employee.getLast_name());
                NurseEntryForm.nicText.setText(employee.getNIC());
                NurseEntryForm.addressText.setText(employee.getAddress());
                NurseEntryForm.genderCombo.setSelectedItem(employee.getSex());
                NurseEntryForm.contactNumberText.setText(employee.getContact_no());
                NurseEntryForm.registrationDateText.setText(employee.getRegistration_date());
                NurseEntryForm.emailText.setText(employee.getEmail());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DetailsGetEmployeeId.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DetailsGetEmployeeId.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nurseIdTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea addressText;
    private javax.swing.JToggleButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JTextField contactNumberText;
    public static javax.swing.JTextField emailText;
    public static javax.swing.JTextField employeeIdText;
    public static javax.swing.JTextField firstNameText;
    public static javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField lastNameText;
    public static javax.swing.JTextField nicText;
    private javax.swing.JPanel nurseEntryFormPanel;
    public static javax.swing.JTextField nurseIdText;
    public static javax.swing.JTextField nurseTypeText;
    public static javax.swing.JTextField registrationDateText;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton updateButton;
    public static javax.swing.JComboBox<String> wardIdCombo;
    // End of variables declaration//GEN-END:variables
}
