/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AdmissionController;
import controller.EmployeeController;
import controller.PatientController;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Patient_record;
import javax.swing.JOptionPane;
import model.Admission;
import static view.Add.addPanel1;

/**
 *
 * @author sanu
 */
public class PatientEntryForm extends javax.swing.JPanel {

    /**
     * Creates new form PatientEntryForm
     */
    public PatientEntryForm() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        patientEntryFormPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        patientIdText = new javax.swing.JTextField();
        firstNameText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        nicText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressText = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bloodGroupCombo = new javax.swing.JComboBox<>();
        ageText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        contactNumberText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        sicknessHistoryText = new javax.swing.JTextArea();
        genderCombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();

        patientEntryFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Patient Entry Form");

        jLabel2.setText("Patient ID");

        jLabel3.setText("First Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("NIC");

        jLabel6.setText("Gender");

        patientIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIdTextActionPerformed(evt);
            }
        });

        nicText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicTextActionPerformed(evt);
            }
        });

        jLabel7.setText("Address");

        addressText.setColumns(20);
        addressText.setRows(5);
        jScrollPane1.setViewportView(addressText);

        jLabel8.setText("Age");

        jLabel9.setText("Blood Group");

        bloodGroupCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        ageText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextActionPerformed(evt);
            }
        });

        jLabel10.setText("Contact Number");

        jLabel11.setText("Sickness History");

        contactNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberTextActionPerformed(evt);
            }
        });

        sicknessHistoryText.setColumns(20);
        sicknessHistoryText.setRows(5);
        jScrollPane2.setViewportView(sicknessHistoryText);

        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/patient.jpg"))); // NOI18N

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patientEntryFormPanelLayout = new javax.swing.GroupLayout(patientEntryFormPanel);
        patientEntryFormPanel.setLayout(patientEntryFormPanelLayout);
        patientEntryFormPanelLayout.setHorizontalGroup(
            patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientEntryFormPanelLayout.createSequentialGroup()
                .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientEntryFormPanelLayout.createSequentialGroup()
                        .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(patientEntryFormPanelLayout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(jLabel1))
                            .addGroup(patientEntryFormPanelLayout.createSequentialGroup()
                                .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(patientEntryFormPanelLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel2))
                                    .addGroup(patientEntryFormPanelLayout.createSequentialGroup()
                                        .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientEntryFormPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel3))
                                            .addGroup(patientEntryFormPanelLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel4))))
                                        .addGap(56, 56, 56)
                                        .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nicText, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(patientIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(firstNameText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(patientEntryFormPanelLayout.createSequentialGroup()
                                        .addGap(114, 114, 114)
                                        .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(patientEntryFormPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(contactNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(patientEntryFormPanelLayout.createSequentialGroup()
                                                .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(patientEntryFormPanelLayout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addGap(129, 129, 129)
                                                        .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(patientEntryFormPanelLayout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addGap(88, 88, 88)
                                                        .addComponent(bloodGroupCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(patientEntryFormPanelLayout.createSequentialGroup()
                                                        .addGap(1, 1, 1)
                                                        .addComponent(jLabel11)))
                                                .addGap(0, 2, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientEntryFormPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientEntryFormPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updateButton)
                        .addGap(148, 148, 148)
                        .addComponent(jButton1)
                        .addGap(317, 317, 317)))
                .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientEntryFormPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientEntryFormPanelLayout.createSequentialGroup()
                        .addComponent(nextButton)
                        .addGap(85, 85, 85))))
        );
        patientEntryFormPanelLayout.setVerticalGroup(
            patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientEntryFormPanelLayout.createSequentialGroup()
                .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(patientEntryFormPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(patientIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(bloodGroupCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(patientEntryFormPanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel4))
                            .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(patientEntryFormPanelLayout.createSequentialGroup()
                                    .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10)
                                        .addComponent(contactNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(35, 35, 35)
                                    .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(nicText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(31, 31, 31)
                                    .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(40, 40, 40)
                                    .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)))
                                .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(69, 69, 69)
                        .addGroup(patientEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(updateButton)))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientEntryFormPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientEntryFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void contactNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Add add = new Add();
        add.addPanel1.setVisible(true);
        patientEntryFormPanel.setLayout(new BorderLayout());
        patientEntryFormPanel.removeAll();
        patientEntryFormPanel.add(addPanel1);
        patientEntryFormPanel.validate();
        patientEntryFormPanel.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ageTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed

        String First_name = firstNameText.getText();
        String Last_name = lastNameText.getText();
        String NIC = nicText.getText();
        String Sex = (String) genderCombo.getSelectedItem();
        String Address = addressText.getText();
        String AgeString = ageText.getText();
        int Age = Integer.parseInt(AgeString);
        String Blood_group = (String) bloodGroupCombo.getSelectedItem();
        String contactNoString = contactNumberText.getText();
        int Contact_no = Integer.parseInt(contactNoString);
        String Sickness_history = sicknessHistoryText.getText();

        Patient_record patient = new Patient_record(First_name, Last_name, NIC, Address, Sex, Age, Blood_group, Contact_no, Sickness_history);
        //Ward ward = new Ward(Ward_type);
        //Receptionist receptionist = 
        try {
            boolean addPatient = PatientController.addPatient(patient);
            if (addPatient) {
                JOptionPane.showMessageDialog(this, "Successful");
            } else {
                JOptionPane.showMessageDialog(this, "Failed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(PatientEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PatientEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        //add AdmissionEntryFormPanel to PatientEntryFormPanel    
        AdmissionEntryForm aef = new AdmissionEntryForm();
        aef.setVisible(true);
        patientEntryFormPanel.setLayout(new BorderLayout());
        patientEntryFormPanel.removeAll();
        patientEntryFormPanel.add(aef);
        patientEntryFormPanel.validate();
        patientEntryFormPanel.repaint();

        //Auto fill admission id to Admission Entry Form
        int admissionId;
        try {
            admissionId = AdmissionController.getLastAdmissionId();
            String aid = new Integer(admissionId + 1).toString();
            aef.admissionIdText.setText(aid);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PatientEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PatientEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Auto fill patient id to Admission Entry Form
        try {
            int patientId = PatientController.getLastPatientId();
            String pid = new Integer(patientId).toString();
            aef.patientIdText.setText(pid);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PatientEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PatientEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Auto fill other details in admission entry form
        String firstName = firstNameText.getText();
        aef.firstNameText.setText(firstName);

        String lastName = lastNameText.getText();
        aef.lastNameText.setText(lastName);

        String nic = nicText.getText();
        aef.nicText.setText(nic);

        String sex = (String) genderCombo.getSelectedItem();
        AdmissionEntryForm.genderCombo.setSelectedItem(sex);

        String address = addressText.getText();
        aef.addressText.setText(address);

        String ageString = ageText.getText();
        int age = Integer.parseInt(ageString);
        aef.ageText.setText(AgeString);

        String bloodGroup = (String) bloodGroupCombo.getSelectedItem();
        AdmissionEntryForm.genderCombo.setSelectedItem(bloodGroup);

        String ContactNoString = contactNumberText.getText();
        int contactNo = Integer.parseInt(ContactNoString);
        aef.contactNoText.setText(contactNoString);

        String sicknessHistory = sicknessHistoryText.getText();
        aef.sicknessHistoryText.setText(sicknessHistory);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void nicTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicTextActionPerformed
//Auto fill patient details when patient id is given to PatientEntryForm
    private void patientIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIdTextActionPerformed
        
        try {
            Patient_record patientRecord = PatientController.searchPatientDetail(patientIdText.getText());
            if (patientRecord != null) {
            //PatientEntryForm.patientIdLabel.setText(patientIdText.getText());
            PatientEntryForm.firstNameText.setText(patientRecord.getFirst_name());
            PatientEntryForm.lastNameText.setText(patientRecord.getLast_name());
            PatientEntryForm.nicText.setText(patientRecord.getNIC());
            PatientEntryForm.addressText.setText(patientRecord.getAddress());
            PatientEntryForm.genderCombo.setSelectedItem(patientRecord.getSex());
            PatientEntryForm.ageText.setText(Integer.toString(patientRecord.getAge()));
            PatientEntryForm.bloodGroupCombo.setSelectedItem(patientRecord.getBlood_group());
            PatientEntryForm.contactNumberText.setText(Integer.toString(patientRecord.getContact_no()));
            PatientEntryForm.sicknessHistoryText.setText(patientRecord.getSickness_history());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewAdmissionGetPatientId.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewAdmissionGetPatientId.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_patientIdTextActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String Patient_id_String = patientIdText.getText();
        int Patient_id = Integer.parseInt(Patient_id_String);
        String First_name = firstNameText.getText();
        String Last_name = lastNameText.getText();
        String NIC = nicText.getText();
        String Sex = (String) genderCombo.getSelectedItem();
        String Address = addressText.getText();
        String AgeString = ageText.getText();
        int Age = Integer.parseInt(AgeString);
        String Blood_group = (String) bloodGroupCombo.getSelectedItem();
        String contactNoString = contactNumberText.getText();
        int Contact_no = Integer.parseInt(contactNoString);
        String Sickness_history = sicknessHistoryText.getText();
       
        Patient_record patient =new Patient_record(Patient_id,First_name, Last_name, NIC, Address, Sex, Age, Blood_group, Contact_no, Sickness_history);
        
        try {
            boolean updatePatient_record = PatientController.UpdatePatient(patient);
            if(updatePatient_record){
            JOptionPane.showMessageDialog(this, "Successful");
            }else{
            JOptionPane.showMessageDialog(this, "Failed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(PatientEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PatientEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea addressText;
    public static javax.swing.JTextField ageText;
    public static javax.swing.JComboBox<String> bloodGroupCombo;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JTextField contactNumberText;
    public static javax.swing.JTextField firstNameText;
    public static javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextField lastNameText;
    private javax.swing.JButton nextButton;
    public static javax.swing.JTextField nicText;
    private javax.swing.JPanel patientEntryFormPanel;
    public static javax.swing.JTextField patientIdText;
    public static javax.swing.JTextArea sicknessHistoryText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
