/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EmployeeController;
import static controller.EmployeeController.getLastEmployeeId;
import controller.ReceptionistController;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Employee;
import model.Receptionist;
import javax.swing.JOptionPane;
import static view.Add.addPanel1;

/**
 *
 * @author sanu
 */
public class ReceptionistEntryForm extends javax.swing.JPanel {

    /**
     * Creates new form ReceptionistEntryForm
     */
    public ReceptionistEntryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        receptionistEntryFormPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        employeeIdText = new javax.swing.JTextField();
        receptionistIdText = new javax.swing.JTextField();
        nicText = new javax.swing.JTextField();
        firstNameText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        receptionistShiftText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        registrationDateText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressText = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        contactNumberText = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        genderCombo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();

        receptionistEntryFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Receptionist Entry Form");

        jLabel2.setText("Employee ID");

        jLabel3.setText("Receptionist ID");

        jLabel4.setText("NIC");

        jLabel5.setText("First Name");

        jLabel6.setText("Last Name");

        jLabel7.setText("Gender");

        receptionistIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptionistIdTextActionPerformed(evt);
            }
        });

        jLabel8.setText("Receptionist Shift");

        jLabel9.setText("Address");

        jLabel10.setText("Registration Date");

        addressText.setColumns(20);
        addressText.setRows(5);
        jScrollPane1.setViewportView(addressText);

        jLabel11.setText("Contact Number");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("Email");

        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/receptionist.jpg"))); // NOI18N

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout receptionistEntryFormPanelLayout = new javax.swing.GroupLayout(receptionistEntryFormPanel);
        receptionistEntryFormPanel.setLayout(receptionistEntryFormPanelLayout);
        receptionistEntryFormPanelLayout.setHorizontalGroup(
            receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receptionistEntryFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(receptionistEntryFormPanelLayout.createSequentialGroup()
                        .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addGroup(receptionistEntryFormPanelLayout.createSequentialGroup()
                                .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(44, 44, 44)
                                .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(employeeIdText, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                            .addComponent(receptionistIdText)
                                            .addComponent(emailText))
                                        .addComponent(lastNameText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nicText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12))
                        .addGap(72, 72, 72)
                        .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(receptionistEntryFormPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(registrationDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(receptionistEntryFormPanelLayout.createSequentialGroup()
                                .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contactNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(receptionistShiftText, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 321, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, receptionistEntryFormPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(268, 268, 268)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(receptionistEntryFormPanelLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel1)
                .addGap(23, 645, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, receptionistEntryFormPanelLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(updateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(490, 490, 490)
                .addComponent(backButton)
                .addGap(59, 59, 59))
        );
        receptionistEntryFormPanelLayout.setVerticalGroup(
            receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receptionistEntryFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(receptionistEntryFormPanelLayout.createSequentialGroup()
                        .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(receptionistEntryFormPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(44, 44, 44)
                                .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(employeeIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(registrationDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(receptionistEntryFormPanelLayout.createSequentialGroup()
                                        .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(receptionistIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                        .addGap(23, 23, 23)
                                        .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(receptionistEntryFormPanelLayout.createSequentialGroup()
                                        .addGap(146, 146, 146)
                                        .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(nicText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(contactNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(jLabel12))
                            .addGroup(receptionistEntryFormPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(receptionistShiftText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(74, 74, 74))
                    .addGroup(receptionistEntryFormPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(receptionistEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(backButton)
                    .addComponent(updateButton))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(receptionistEntryFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(receptionistEntryFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //String Employee_id_String = employeeIdText.getText();
        //int Employee_id = Integer.parseInt(Employee_id_String);
        //String Receptionist_id_String = receptionistIdText.getText();
        //int Receptionist_id = Integer.parseInt(Receptionist_id_String);
        String Receptionist_shift = receptionistShiftText.getText();
        String First_name = firstNameText.getText();
        String Last_name = lastNameText.getText();
        String NIC = nicText.getText();
        String Address = addressText.getText();
        String Sex = (String)genderCombo.getSelectedItem();
        String Contact_no = contactNumberText.getText();
        String Registration_date = registrationDateText.getText();
        String Email = emailText.getText();
      
        
        //Receptionist reseptionist = new Receptionist(Employee_id,Receptionist_id,Receptionist_shift);
        Receptionist receptionist = new Receptionist(Receptionist_shift,First_name,Last_name,NIC,Address,Sex,Contact_no,Registration_date,Email);
        try {
            receptionist.setEmployee_id(getLastEmployeeId());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReceptionistEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ReceptionistEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            EmployeeController.addEmployee(receptionist);
            boolean addReceptionist = ReceptionistController.addReceptionist(receptionist);
            if(addReceptionist){
                JOptionPane.showMessageDialog(this, "Successful");
            }else{
                JOptionPane.showMessageDialog(this, "Failed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReceptionistEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReceptionistEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Add add = new Add();
        add.addPanel1.setVisible(true);
        receptionistEntryFormPanel.setLayout(new BorderLayout());
        receptionistEntryFormPanel.removeAll();
        receptionistEntryFormPanel.add(addPanel1);
        receptionistEntryFormPanel.validate();
        receptionistEntryFormPanel.repaint();
    }//GEN-LAST:event_backButtonActionPerformed

    private void receptionistIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptionistIdTextActionPerformed
       //Auto fill receptionist detail
        Receptionist receptionist;
        try {
            receptionist = ReceptionistController.searchReceptionistDetail(receptionistIdText.getText());
            if (receptionist != null) {
            //ReceptionistDetailForm.receptionistIdLabel.setText(receptionistIdText.getText());
            ReceptionistEntryForm.receptionistShiftText.setText(receptionist.getReceptionist_shift());
            ReceptionistEntryForm.employeeIdText.setText(Integer.toString(receptionist.getEmployee_Employee_id()));}
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DetailsGetReceptionistId.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DetailsGetReceptionistId.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Employee employee = null;
        try {
            employee = EmployeeController.searchEmployeeDetail(employeeIdText.getText());
            if (employee != null) {
                ReceptionistEntryForm.employeeIdText.setText(employeeIdText.getText());
                ReceptionistEntryForm.firstNameText.setText(employee.getFirst_name());
                ReceptionistEntryForm.lastNameText.setText(employee.getLast_name());
                ReceptionistEntryForm.nicText.setText(employee.getNIC());
                ReceptionistEntryForm.addressText.setText(employee.getAddress());
                ReceptionistEntryForm.genderCombo.setSelectedItem(employee.getSex());
                ReceptionistEntryForm.contactNumberText.setText(employee.getContact_no());
                ReceptionistEntryForm.registrationDateText.setText(employee.getRegistration_date());
                ReceptionistEntryForm.emailText.setText(employee.getEmail());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DetailsGetEmployeeId.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DetailsGetEmployeeId.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_receptionistIdTextActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String Employee_id_String = employeeIdText.getText();
        int Employee_id = Integer.parseInt(Employee_id_String); 
        String Receptionist_id_String = receptionistIdText.getText();
        int Receptionist_id = Integer.parseInt(Receptionist_id_String); 
        String NIC = nicText.getText();
        String First_name = firstNameText.getText();
        String Last_name = lastNameText.getText();
        String Sex = (String)genderCombo.getSelectedItem();
        String Email = emailText.getText();
        String Registration_date = registrationDateText.getText();
        String Address = addressText.getText();
        String Receptionist_shift = receptionistShiftText.getText();
        String Contact_no = contactNumberText.getText();
        
        Receptionist receptionist = new Receptionist(Receptionist_id,Receptionist_shift,Employee_id, First_name, Last_name, NIC, Address, Sex, Contact_no, Registration_date, Email);
        
        try {
            boolean updateEmployee=EmployeeController.updateEmployee(receptionist);
            boolean updateReceptionist = ReceptionistController.UpdateReceptionist(receptionist);
            if(updateReceptionist){
            JOptionPane.showMessageDialog(this, "Successful");
            }else{
            JOptionPane.showMessageDialog(this, "Failed");
            }
            if(updateEmployee){
            JOptionPane.showMessageDialog(this, "Su");
            }else{
            JOptionPane.showMessageDialog(this, "Fa");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReceptionistEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReceptionistEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea addressText;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JTextField contactNumberText;
    public static javax.swing.JTextField emailText;
    public static javax.swing.JTextField employeeIdText;
    public static javax.swing.JTextField firstNameText;
    public static javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField lastNameText;
    public static javax.swing.JTextField nicText;
    private javax.swing.JPanel receptionistEntryFormPanel;
    public static javax.swing.JTextField receptionistIdText;
    public static javax.swing.JTextField receptionistShiftText;
    public static javax.swing.JTextField registrationDateText;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
