/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author sanu
 */
public class ReceptionistDetailForm extends javax.swing.JPanel {

    /**
     * Creates new form ReceptionistDetailForm
     */
    public ReceptionistDetailForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receptionistDetailPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        receptionistIdLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        receptionistShiftLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        getEmployeeIdLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nicLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        registrationDateLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        contactNoLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Receptionist Detail Form");

        jLabel2.setText("Receptionist Id");

        receptionistIdLabel.setText("---------------------------------------------------");

        jLabel3.setText("Receptionist Shift");

        receptionistShiftLabel.setText("---------------------------------------------------");

        jLabel4.setText("Employee Id");

        getEmployeeIdLabel.setText("---------------------------------------------------");

        jLabel5.setText("First Name");

        jLabel6.setText("Last Name");

        firstNameLabel.setText("--------------------------------------------------");

        lastNameLabel.setText("---------------------------------------------------");

        jLabel7.setText("NIC");

        jLabel8.setText("Gender");

        jLabel9.setText("Email");

        nicLabel.setText("---------------------------------------------------");

        genderLabel.setText("--------------------------------------------------");

        emailLabel.setText("--------------------------------------------------");

        jLabel10.setText("Registration Date");

        jLabel11.setText("Address");

        jLabel12.setText("Contact Number");

        registrationDateLabel.setText("----------------------------------------------------");

        addressLabel.setText("----------------------------------------------------");

        contactNoLabel.setText("---------------------------------------------------");

        javax.swing.GroupLayout receptionistDetailPanelLayout = new javax.swing.GroupLayout(receptionistDetailPanel);
        receptionistDetailPanel.setLayout(receptionistDetailPanelLayout);
        receptionistDetailPanelLayout.setHorizontalGroup(
            receptionistDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, receptionistDetailPanelLayout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(273, 273, 273))
            .addGroup(receptionistDetailPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(receptionistDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(35, 35, 35)
                .addGroup(receptionistDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(receptionistIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(getEmployeeIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(receptionistDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(56, 56, 56)
                .addGroup(receptionistDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(receptionistDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(receptionistShiftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(registrationDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                        .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(contactNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        receptionistDetailPanelLayout.setVerticalGroup(
            receptionistDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receptionistDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(receptionistDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(getEmployeeIdLabel)
                    .addComponent(jLabel10)
                    .addComponent(registrationDateLabel))
                .addGap(32, 32, 32)
                .addGroup(receptionistDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(receptionistIdLabel)
                    .addComponent(jLabel11)
                    .addComponent(addressLabel))
                .addGap(35, 35, 35)
                .addGroup(receptionistDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(firstNameLabel)
                    .addComponent(jLabel12)
                    .addComponent(contactNoLabel))
                .addGap(31, 31, 31)
                .addGroup(receptionistDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lastNameLabel)
                    .addComponent(jLabel3)
                    .addComponent(receptionistShiftLabel))
                .addGap(37, 37, 37)
                .addGroup(receptionistDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nicLabel))
                .addGap(37, 37, 37)
                .addGroup(receptionistDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(genderLabel))
                .addGap(34, 34, 34)
                .addGroup(receptionistDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(emailLabel))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(receptionistDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(receptionistDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel addressLabel;
    public static javax.swing.JLabel contactNoLabel;
    public static javax.swing.JLabel emailLabel;
    public static javax.swing.JLabel firstNameLabel;
    public static javax.swing.JLabel genderLabel;
    public static javax.swing.JLabel getEmployeeIdLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel lastNameLabel;
    public static javax.swing.JLabel nicLabel;
    private javax.swing.JPanel receptionistDetailPanel;
    public static javax.swing.JLabel receptionistIdLabel;
    public static javax.swing.JLabel receptionistShiftLabel;
    public static javax.swing.JLabel registrationDateLabel;
    // End of variables declaration//GEN-END:variables
}
