/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AdmissionHasTestController;
import controller.TestController;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.AdmissionHasTest;
import model.Test;
import static view.Add.addPanel1;

/**
 *
 * @author sanu
 */
public class TestEntryForm extends javax.swing.JPanel {

    /**
     * Creates new form TestEntryForm
     */
    public TestEntryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testEntryFormPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        resultsCombo = new javax.swing.JComboBox<>();
        testIdText = new javax.swing.JTextField();
        admissionIdText = new javax.swing.JTextField();
        doctorIdText = new javax.swing.JTextField();
        testCategoryText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        trdText = new javax.swing.JTextArea();
        dateText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        submitButton = new javax.swing.JToggleButton();
        backButton = new javax.swing.JToggleButton();
        updateButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Test Entry Form");

        jLabel2.setText("Test ID");

        jLabel3.setText("Test Category");

        jLabel4.setText("Admission ID");

        jLabel5.setText("Doctor ID");

        jLabel6.setText("Test Results description");

        jLabel7.setText("Date");

        resultsCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pass", "Fail", "Other" }));

        testIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testIdTextActionPerformed(evt);
            }
        });

        admissionIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admissionIdTextActionPerformed(evt);
            }
        });

        trdText.setColumns(20);
        trdText.setRows(5);
        jScrollPane1.setViewportView(trdText);

        dateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextActionPerformed(evt);
            }
        });

        jLabel8.setText("Result");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout testEntryFormPanelLayout = new javax.swing.GroupLayout(testEntryFormPanel);
        testEntryFormPanel.setLayout(testEntryFormPanelLayout);
        testEntryFormPanelLayout.setHorizontalGroup(
            testEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testEntryFormPanelLayout.createSequentialGroup()
                .addGroup(testEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(testEntryFormPanelLayout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(jLabel1))
                    .addGroup(testEntryFormPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(testEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(testEntryFormPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(testEntryFormPanelLayout.createSequentialGroup()
                                .addGroup(testEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(56, 56, 56)
                                .addGroup(testEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(testIdText)
                                    .addComponent(admissionIdText)
                                    .addComponent(doctorIdText)
                                    .addComponent(testCategoryText, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                                .addGap(221, 221, 221)
                                .addGroup(testEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(25, 25, 25)
                                .addGroup(testEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resultsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, testEntryFormPanelLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(updateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(297, 297, 297)
                .addComponent(backButton)
                .addGap(53, 53, 53))
        );
        testEntryFormPanelLayout.setVerticalGroup(
            testEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testEntryFormPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(testEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(testIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(testEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(admissionIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(34, 34, 34)
                .addGroup(testEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(doctorIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(testEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(testCategoryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(testEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(testEntryFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(backButton)
                    .addComponent(updateButton))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(testEntryFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(testEntryFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void testIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testIdTextActionPerformed

    private void dateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String AdmissionIdString = admissionIdText.getText();
        int Admission_id = Integer.parseInt(AdmissionIdString);
        String DoctorIdString = doctorIdText.getText();
        int Doctor_id = Integer.parseInt(DoctorIdString);
        String Category = testCategoryText.getText();
        String Description = trdText.getText();
        String Date = dateText.getText();
        String Result = (String)resultsCombo.getSelectedItem();
        
        int Test_id = 0;
        try {
            Test_id = TestController.getLastTestId()+1;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TestEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TestEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Test test = new Test(Doctor_id,Category,Description,Date,Result);
        AdmissionHasTest ahs = new AdmissionHasTest(Admission_id,Test_id);
        
        try {
            boolean addTest = TestController.addTest(test);
            boolean addAHT = AdmissionHasTestController.addAdmissionHasTest(ahs);
            if(addTest){
                JOptionPane.showMessageDialog(this, "Successful");
            }else{
                JOptionPane.showMessageDialog(this, "Failed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TestEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TestEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Add add = new Add();
        add.addPanel1.setVisible(true);
        testEntryFormPanel.setLayout(new BorderLayout());
        testEntryFormPanel.removeAll();
        testEntryFormPanel.add(addPanel1);
        testEntryFormPanel.validate();
        testEntryFormPanel.repaint();
    }//GEN-LAST:event_backButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String Test_id_String = testIdText.getText();
        int Test_id = Integer.parseInt(Test_id_String); 
        String Admission_id_String = admissionIdText.getText();
        int Admission_id = Integer.parseInt(Admission_id_String); 
        String Doctor_id_String = doctorIdText.getText();
        int Doctor_id = Integer.parseInt(Doctor_id_String); 
        String Category = testCategoryText.getText();
        String Description = trdText.getText();
        String Date = dateText.getText();
        String Result = (String)resultsCombo.getSelectedItem();
        
        Test test = new Test(Test_id,Doctor_id,Category,Description,Date,Result);
         AdmissionHasTest ahs = new AdmissionHasTest(Admission_id,Test_id);
        
        try {
            boolean updateTest = TestController.UpdateTest(test);
            //boolean updateAHT = AdmissionHasTestController.UpdateAdmissionHasTest(ahs);
            if(updateTest){
            JOptionPane.showMessageDialog(this, "Successful");
            }else{
            JOptionPane.showMessageDialog(this, "Failed");
            }
            /*if(updateAHT){
            JOptionPane.showMessageDialog(this, "Su");
            }else{
            JOptionPane.showMessageDialog(this, "Fa");
            */
        } catch (SQLException ex) {
            Logger.getLogger(TestEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TestEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void admissionIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admissionIdTextActionPerformed
        //Auto fill test id
        try {
            AdmissionHasTest admissionHasTest = AdmissionHasTestController.searchAdmissionId(admissionIdText.getText());
            if (admissionHasTest!=null){
                TestEntryForm.testIdText.setText(Integer.toString(admissionHasTest.getTest_Test_id()));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TestEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TestEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         //auto fill other test details
        try {
            Test test = TestController.searchTestDetail(testIdText.getText());
            if (test!=null){
                TestEntryForm.doctorIdText.setText(Integer.toString(test.getDoctor_id()));
                TestEntryForm.testCategoryText.setText(test.getCategory());
                TestEntryForm.trdText.setText(test.getDescription());
                TestEntryForm.dateText.setText(test.getDate());
                TestEntryForm.resultsCombo.setSelectedItem(test.getCategory());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TestEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TestEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_admissionIdTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField admissionIdText;
    private javax.swing.JToggleButton backButton;
    public static javax.swing.JTextField dateText;
    public static javax.swing.JTextField doctorIdText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JComboBox<String> resultsCombo;
    private javax.swing.JToggleButton submitButton;
    public static javax.swing.JTextField testCategoryText;
    private javax.swing.JPanel testEntryFormPanel;
    public static javax.swing.JTextField testIdText;
    public static javax.swing.JTextArea trdText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
